name: Deploy VueJS Project

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Dependencies
        run: npm install
      - name: Build App
        run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3 
      - name: Deploy to Netlify
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/67a6171d88909214e5cbaab9
