name: Remove old artifacts

on:
  schedule:
    # every day at 1 am
    - cron: '0 1 * * *'

jobs:
 remove-old-artifacts:
   runs-on: ubuntu-latest
   timeout-minutes: 10

   permissions:
     actions: write

   steps:
   - name: Remove old artifacts
     uses: c-hive/gha-remove-artifacts@v1
     with:
       age: '1 day'
